version: 2
jobs:
  build:
    resource_class: large
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
    steps:
      - checkout
      - run:
          name: Decode API Keys and Secrets
          command: |
            echo $FIREBASE_API_JSON  | base64 --decode > app/google-services.json
            echo $SECRETS_PROPERTIES | base64 --decode > app/secrets.properties

      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
            - gradle-

      - restore_cache:
          key: android-cache-

      - run:
          name: Start Gradle Daemon
          command: nohup ./gradlew

      - run:
          name: Install Dependencies
          command: ./gradlew app:dependencies

      - run:
          name: Build Tests
          command: ./gradlew assembleEnvProdMinApi21Debug -Dpre-dex=false -Pkotlin.incremental=false

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - save_cache:
          key: android-cache-{{ epoch }}
          paths:
            - ~/.android/build-cache
            - ~/.android/cache

      - run:
          name: Run Tests
          command: ./gradlew testEnvProdMinApi21DebugUnitTest testEnvProdMinApi21DebugUnitTestCoverage coveralls -Dpre-dex=false -Pkotlin.incremental=false 

      - store_artifacts:
          path: app/build/reports
          destination: Test Reports
      - store_artifacts:
          path: build/test-results
          destination: Test Result XML
      - store_test_results:
          path: build/test-results

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN